blank_issues_enabled: false
contact_links:
  - name: NEU Support
    url: https://discord.gg/moulberry
    about: "Please ask for support in #neu-support on Moulberrys discord."
  - name: Report security vulnerabilitie
    url: https://discord.gg/moulberry
    about: "If you wish to discuss a bug *with security implications* privately, please open a ticket in Moulberrys discord using /new in #bot-commands"
