name: Pre-Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    env:
      GIT_URL: ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.sha }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Set up gradle cache
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: |
          ./gradlew test
          ./gradlew clean
          ./gradlew includeBackupRepo
          ./gradlew remapJar
        env:
          NEU_RELEASE: true
      - uses: actions/upload-artifact@v4
        with:
          path: build/libs/*.jar
      - run: ./.github/workflows/upload-release.sh
        env:
          GH_TOKEN: ${{ github.token }}
